name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']  # Supported Python versions, you can adjust them

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment for each version in the matrix
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Flask>=2.0.0
          pip install Flask-SQLAlchemy>=2.5.0
          pip install python-dotenv>=0.21.0
          pip install flask_login==0.6.2
          pip install flask_wtf==1.1.1
          pip install gunicorn==20.1.0
          pip install pytest  # Added pytest as it's required for testing
          pip install black   # Added black for code formatting
          pip install bandit  # Added bandit for security scanning

      # Step 4: Format the code using Black
      - name: Format code with Black
        run: |
          black .

      # Step 5: Run a security scan with Bandit, ignoring specific warning (B104)
      - name: Run security scan with Bandit
        run: |
          bandit -r . -s B104  # Ignore the B104 warning specifically

      # Step 6: Run tests using pytest and generate a test report
      - name: Run Tests
        run: |
          pytest tests/ --junitxml=pytest.xml  # Adjust test location as needed + create a report

      # Step 7: Upload test results as an artifact
      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: pytest.xml
