name: CI Pipeline

on:
  push:
    branches:
      - main  # Replace with your main branch name if different

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']  # Supported Python versions

    steps:
      # Step 1: Checkout code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python for each version in the matrix
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}  # Use Python version from the matrix

      # Step 3: Install project dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Ensure your project includes a requirements.txt file

      # Step 4: Format the code with Black for consistent styling
      - name: Format code with Black
        run: |
          black .

      # Step 5: Run security scan with Bandit and ignore B104 warning
      - name: Run security scan with Bandit
        run: |
          bandit -r . --skip B104  # Correctly ignore B104 warning

      # Step 6: Run tests with pytest and generate a report
      - name: Run Tests
        run: |
          pytest --junitxml=pytest.xml  # Adjust test location as needed + create a report

      # Step 7: Upload the test results as an artifact
      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: pytest.xml  # Upload the test result file
