name: CI Pipeline

on:
  push:
    branches:
      - main  # Replace with your main branch name if it's different

jobs:
  build-and-test:
    runs-on: ubuntu-latest  # Using the latest Ubuntu runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Check out the repository code

      - name: Set up Python
        uses: actions/setup-python@v4  # Set up Python environment
        with:
          python-version: '3.10'  # Specify your desired Python version (e.g., 3.10)

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # Upgrade pip to the latest version
          pip install -r requirements.txt  # Install dependencies from requirements.txt

      - name: Run Tests
        run: |
          pytest  # This assumes your test files are in the default location
          # If your test files are in a folder named "tests", use:
          # pytest tests/
